# Generated by Django 2.2 on 2021-07-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.CharField(choices=[('1', 'Text'), ('2', 'Radio'), ('3', 'Checkbox')], max_length=1)),
                ('text', models.CharField(max_length=300)),
                ('poll', models.ManyToManyField(to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
