# Generated by Django 2.2 on 2021-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
