# Generated by Django 2.2 on 2021-07-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210711_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_3',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_answer', models.CharField(blank=True, default='', help_text='max 50 simbols', max_length=50, null=True)),
                ('variant1', models.CharField(blank=True, default='', help_text='max 50 simbols', max_length=50, null=True)),
                ('variant2', models.CharField(blank=True, default='', help_text='max 50 simbols', max_length=50, null=True)),
                ('variant3', models.CharField(blank=True, default='', help_text='max 50 simbols', max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
